### ISSUE TITLE
the files example_german.json, example_piano.json are not valid json

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-trigger-action-on-note#3]
The example with the German-English deck is very useful but the file `example_german.json` is not valid json: The add-on config window complains about the end of the second line which is a quick fix. The file `example_piano.json` is also not valid json and not accepted by the anki add-on config window. 

P.S.: Thanks for creating and freely sharing this add-on. Also thanks for creating multiple instructive examples.

**Comment by Arthur-Milchior** [comment]
Thank you for the notification. Corrected. And you're welcome

**Comment by ijgnd** [comment]
thanks for the quick fix.
