### ISSUE TITLE
update description 

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-trigger-action-on-note#4]
It took me some time to figure out how to run this add-on. The only way to run it at the moment seems to be from the browser. But the word "browser" does not occur on the description on ankiweb and not in README.md in this repo. 

Maybe update the description with this paragraph from [your reddit thread](https://www.reddit.com/r/Anki/comments/d6e7pm/more_intelligent_note_system_allow_to_change_a/) which has "Currently, you have to select notes in the browser and state you want to apply rules to them."

**Comment by Arthur-Milchior** [comment]
Done. Thanks; I don't know why I did forget to do it
