### ISSUE TITLE
typo in readme.md?

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-trigger-action-on-note#6]
In [the examples section of your readme.md](https://github.com/Arthur-Milchior/anki-trigger-action-on-note/blob/master/README.md#examples) you write:

> My card types are big, so you may want to use add-on 1482505492 to makes anki quicker before taking a look at them in details.

The add-on 1482505492 is [Merge two notes into a single note](https://ankiweb.net/shared/info/1482505492).

Isn't it [3 add-ons merged: quicker anki, explain deletion, explain database check](https://ankiweb.net/shared/info/777545149)?

**Comment by Arthur-Milchior** [comment]
Thanks
